#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the boot_user.mk file instead.
#

# Constants automatically defined by the selected modules
boot_DEBUG = 1

# Our target application
TRG += boot

boot_PREFIX = "arm-none-eabi-"

boot_SUFFIX = ""

boot_SRC_PATH = boot

boot_HW_PATH = boot/hw

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CSRC INSTEAD!
boot_WIZARD_CSRC = \
	bertos/algo/crc_ccitt.c \
	bertos/mware/event.c \
	bertos/drv/eeprom.c \
	bertos/io/kfile.c \
	bertos/mware/formatwr.c \
	bertos/io/kblock.c \
	bertos/mware/sprintf.c \
	bertos/drv/i2c.c \
	bertos/drv/i2c_bitbang.c \
	$(boot_HW_PATH)/hw_i2c_bitbang.c \
	bertos/io/kfile_block.c \
	bertos/drv/timer.c \
	bertos/kern/signal.c \
	bertos/kern/proc.c \
	bertos/mware/hex.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/cpu/cortex-m3/drv/eth_stm32.c \
	bertos/cpu/cortex-m3/drv/flash_stm32.c \
	bertos/net/tftp.c \
	$(LWIP_BERTOS_FILES) \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_PCSRC INSTEAD!
boot_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CPPASRC INSTEAD!
boot_WIZARD_CPPASRC = \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_CXXSRC INSTEAD!
boot_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE boot_USER_ASRC INSTEAD!
boot_WIZARD_ASRC = \
	 \
	#

boot_CPPFLAGS = -D'CPU_FREQ=(106000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(boot_HW_PATH) -I$(boot_SRC_PATH) $(boot_CPU_CPPFLAGS) $(boot_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_LDFLAGS = $(boot_CPU_LDFLAGS) $(boot_WIZARD_LDFLAGS) $(boot_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPPAFLAGS = $(boot_CPU_CPPAFLAGS) $(boot_WIZARD_CPPAFLAGS) $(boot_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CSRC = $(boot_CPU_CSRC) $(boot_WIZARD_CSRC) $(boot_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_PCSRC = $(boot_CPU_PCSRC) $(boot_WIZARD_PCSRC) $(boot_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPPASRC = $(boot_CPU_CPPASRC) $(boot_WIZARD_CPPASRC) $(boot_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CXXSRC = $(boot_CPU_CXXSRC) $(boot_WIZARD_CXXSRC) $(boot_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_ASRC = $(boot_CPU_ASRC) $(boot_WIZARD_ASRC) $(boot_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
boot_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S
boot_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
boot_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F207IG__
boot_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c
boot_PROGRAMMER_CPU = stm32
boot_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f207ig_rom.ld
boot_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
boot_CPU = cortex-m3
boot_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
boot_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
boot_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh


include $(boot_SRC_PATH)/boot_user.mk
